language: python
dist: bionic
virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-venv

install:
  - bash activate

script:
  - make static
  - make test
