name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
      
      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@v0.0.0
        with:
          geckodriver-version: 0.29.0

      - name: Test
        run: |
          sudo apt update
          sudo apt install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libcap2-bin grep xz-utils file
          source activate
          make raspbian_image
          ls dist
      
